// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBsfISwvZMG7y1ffar-69sivEhNb7Lsz3E',
    appId: '1:876145567306:web:33c76f00ae4d82d54868b3',
    messagingSenderId: '876145567306',
    projectId: 'todo-list-firebase-410bf',
    authDomain: 'todo-list-firebase-410bf.firebaseapp.com',
    storageBucket: 'todo-list-firebase-410bf.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC6a7AgB-w7t_8ZBb7UjAy-TDP1gxiC4F8',
    appId: '1:876145567306:android:69f62a3914638b024868b3',
    messagingSenderId: '876145567306',
    projectId: 'todo-list-firebase-410bf',
    storageBucket: 'todo-list-firebase-410bf.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAEGN-eU2yvMBbbw2DEIZpIQaqQMMfbliY',
    appId: '1:876145567306:ios:db805d5f9397f10a4868b3',
    messagingSenderId: '876145567306',
    projectId: 'todo-list-firebase-410bf',
    storageBucket: 'todo-list-firebase-410bf.appspot.com',
    iosBundleId: 'com.example.flutterFirestore',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAEGN-eU2yvMBbbw2DEIZpIQaqQMMfbliY',
    appId: '1:876145567306:ios:fc808ef81810d8834868b3',
    messagingSenderId: '876145567306',
    projectId: 'todo-list-firebase-410bf',
    storageBucket: 'todo-list-firebase-410bf.appspot.com',
    iosBundleId: 'com.example.flutterFirestore.RunnerTests',
  );
}
